GoogolNotes/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import urls as accounts_urls
from app import urls as app_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(accounts_urls)),
    path('', include(app_urls))
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views as accounts_views


app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', accounts_views.SignupView.as_view(), name='signup'),
]

app/urls.py
from django.urls import path
from . import views as v

app_name = 'app'

urlpatterns = [
    path('', v.HomePageListView.as_view(), name='all-notes'),
    path('note/new', v.NoteCreateView.as_view(), name='create-note'),
    path('note/detail/<int:pk>/', v.NoteDetailView.as_view(), name='detail-note'),
    path('note/update/<int:pk>/', v.NoteEditView.as_view(), name='update-note'),
    path('note/delete/<int:pk>/', v.NoteDeleteView.as_view(), name='delete-note'),
    path('note/search/', v.note_search, name='search-note')
]

accounts/models.py
from django.db import models
from django.contrib import auth


# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return str(self.username)

app/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
import misaka

# Create your models here.
User = get_user_model()


class Note(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    date = models.DateTimeField(auto_now=True)
    note = models.TextField()
    note_html = models.TextField(editable=False, default='', blank=True)
    related_tag = models.CharField(
        max_length=256, null=True, blank=True, default='No Related Tag(s)')

    def __str__(self):
        return str(self.title)

    def save(self, *args, **kargs):
        self.note_html = misaka.html(self.note)
        super().save(*args, *kargs)

    def get_absolute_url(self):
        return reverse('app:all-notes')

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    fields = ("username", "password1", "password2",
              "email", "first_name", "last_name")
    model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].help_text = None
        self.fields['username'].label = "Username"
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from .forms import UserCreateForm
from django.views.generic import CreateView

# Create your views here.


class SignupView(CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'accounts/signup.html'

app/views.py
from django.shortcuts import render
from django.views import generic
from .models import Note
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy

# Create your views here.


class HomePageListView(LoginRequiredMixin, generic.ListView):
    model = Note


class NoteCreateView(LoginRequiredMixin, generic.CreateView):
    model = Note
    fields = ('title', 'note', 'related_tag')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class NoteDetailView(LoginRequiredMixin, generic.DetailView):
    model = Note


class NoteEditView(LoginRequiredMixin, generic.UpdateView):
    model = Note
    fields = ('title', 'note', 'related_tag')
    template_name = 'app/note_update.html'


class NoteDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Note
    success_url = reverse_lazy('app:all-notes')


def note_search(request):
    query = request.GET.get('q')
    queryset = Note.objects.all()

    if query:
        queryset = queryset.filter(related_tag__icontains=query)

    return render(request, 'app/note_search.html', {'results': queryset})

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block title  %}Googol Notes- Login Portal{% endblock title  %}

{% block content %}

<div class="card" style="width: 25rem; margin: auto; padding: 10px; margin-top: 100px;">
  <div class="card-body">
  	<img src="{% static 'imgs/favicon.png' %}" class="icon">
  	<strong style="margin-left: 120px;">Googol Notes</strong><br><br>
    <h5 class="card-title">Log Back Into Your Account!</h5>
    <h6 class="card-subtitle mb-2 text-muted">Login Back In To Access Your Notes!</h6><br>
    <form method="POST">
    	{% csrf_token %}
    	{{ form.as_p }}
    	<input type="submit" value='Login' class="btn btn-outline-success">
      <a href="{% url 'accounts:signup' %}" style="margin-left: 90px; text-decoration: none;">Not A Member? Signup</a>
    </form>
  </div>
</div>
{% endblock content %}

templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}

{% block title  %}Googol Notes- Signup Portal{% endblock title  %}

{% block content %}
<div class="card" style="width: 25rem; margin: auto; padding: 10px; margin-top: 100px;">
  <div class="card-body">
  	<img src="{% static 'imgs/favicon.png' %}" class="icon">
  	<strong style="margin-left: 120px;">Googol Notes</strong><br><br>
    <h5 class="card-title">Not Already A Member? Signup!</h5>
    <h6 class="card-subtitle mb-2 text-muted">Create A Account And Store Your Notes!</h6><br>
    <form method="POST">
    	{% csrf_token %}
    	{{ form.as_p }}
    	<input type="submit" value='Signup' class="btn btn-outline-primary">
    	<a href="{% url 'accounts:login' %}" style="margin-left: 150px; text-decoration: none;">Login Instead</a>
    </form>
  </div>
</div>
{% endblock content %}

templates/app/note_confirm_delete.html
{% extends 'base.html' %}
{% block title %}
Confirm Your Deletion
{% endblock title %}

{% block content %}
<div class="container center-text">
		<h3>Are You Sure You Want To Delete "{{ object }}" ?</h3><br>
		<form method="POST">
			{% csrf_token %}
			<a autofocus href="{% url 'app:detail-note' pk=object.pk %}" class="btn btn btn-primary">No Take Me Back</a><br><br>
			<input type="submit" value='Delete' class="btn btn-sm btn-outline-danger">
		</form>
</div>
{% endblock content %}

templates/app/note_detail.html
{% extends 'base.html' %}

{% block title %}
Googol Notes - {{ object.title }} Details 
{% endblock title %}

{% block content %}
<br>
<h2>{{ object.title }} Details</h2>
Tagged: {{ object.related_tag }}

<p>Date Created: {{ object.date }}</p>
<hr style="background: rgba(0, 0, 0, 0.1);">
<p><br>
{{ object.note_html|safe|linebreaks }}
</p>
<hr style="background: rgba(0, 0, 0, 0.1);">
<a href="{% url 'app:update-note' pk=object.pk %}" style="color: white"><button class="btn btn-lg btn-outline-warning"><i class="fa fa-pencil" aria-hidden="true"></i></button></a>
<a href="{% url 'app:delete-note' pk=object.pk %}" style="color: white"><button class="btn btn-lg btn-outline-danger"><i class="fa fa-trash" aria-hidden="true"></i></button></a>
<br><br>
{% endblock content %}

templates/app/note_form.html
{% extends 'base.html' %}
{% block title %}Googol Notes -  Create A New Note{% endblock title %}


{% block content %}
<div class="container">
	<form method="POST" spellcheck="false">
		{% csrf_token %}
		{{ form.as_p }}
		<br><br>
		<input type="submit" value='Create' class="btn btn-outline-primary"><br><br>
	</form>
</div>
{% endblock content %}

templates/app/note_list.html
{% extends 'base.html' %}

{% block title  %}Googol Notes- All Your Notes{% endblock title  %}

{% block content %}
<br><br>
<div class="row">
{% for object in object_list %}
	{% if object.user == user %}
	<div class="col-sm-6">
		<div class="card">
		  <div class="card-body">
		    <h5 class="card-title">{{ object.title }}</h5>
		    <h6 class="card-subtitle mb-2 text-muted">{{ object.related_tag }}</h6><br>
		    <a href="{% url 'app:detail-note' pk=object.pk %}" class="card-link btn btn-sm btn-outline-primary">View</a>
		    <a href="{% url 'app:delete-note' pk=object.pk %}" class="card-link btn btn-sm btn-outline-danger">Delete</a><br><br>
		    <small class="card-subtitle mb-2 text-muted">{{ object.date }}</small>
		  </div>
		</div><br><br>
	</div>
	{% endif %}
	{% empty %}
	<div class="container center-text">
		<h3>There Are No Notes In Your Account Right Now.</h3>
	</div>
{% endfor %}
</div>

<div class="new-note">
	<a href="{% url 'app:create-note' %}"><button class="btn btn-lg new-note-btn"><i style="color: white;" class="fa fa-plus" aria-hidden="true"></i></button></a>
</div>
{% endblock content %}

templates/app/note_search.html
{% extends 'base.html' %}

{% block title %}
Googol Notes - Search Notes
{% endblock title %}

{% block content %}
<form method="GET" style="margin-left: 15px;">
  <div class="form-group">
    <label for="q">Search A Note Tag</label>
    <input type="text" class="form-control" id="q" name="q">
  </div>
  <button type="submit" class="btn btn-primary">Search</button>
</form><br><br>


<div class="row" style="margin-left: 1px;">
{% for result in results %}
{% if result.user == user %}
<div class="col-sm-6">
	<div class="card">
	  <div class="card-body">
	    <h5 class="card-title">{{ result.title }}</h5>
	    <h6 class="card-subtitle mb-2 text-muted">{{ result.related_tag }}</h6><br>
	    <a href="{% url 'app:detail-note' pk=result.pk %}" class="card-link btn btn-sm btn-outline-primary">View</a>
	    <a href="{% url 'app:delete-note' pk=result.pk %}" class="card-link btn btn-sm btn-outline-danger">Delete</a><br><br>
	    <small class="card-subtitle mb-2 text-muted">{{ result.date }}</small>
	  </div>
	</div><br><br>
</div>
{% endif %}
{% empty %}
<div class="container center-text">
	<h3>There Are No Notes In Your Account Right Now With This Tag!</h3>
</div>
{% endfor %}
</div>
{% endblock content %}

templates/app/note_update.html
{% extends 'base.html' %}
{% block title %}Googol Notes -  Update Note {{ object }}{% endblock title %}


{% block content %}
<div class="container">
	<form method="POST" spellcheck="false">
		{% csrf_token %}
		{{ form.as_p }}
		<br><br>
		<input type="submit" value='Update' class="btn btn-outline-primary"><br><br>
	</form>
</div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
		<title>{% block title %}{% endblock title %}</title>
		<!-- Bootstrap -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
		<!-- Google Fonts -->
		<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700;1,800&display=swap" rel="stylesheet">
		<!-- Stylesheet -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">
		<!-- Font Awesome -->
		<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<!-- Favicon -->
		<link rel="shortcut icon" type="icon/svg" href="{% static 'imgs/favicon.png' %}">
</head>
<body>

	<!-- Nav -->
	<nav class="navbar fixed-top navbar-expand-md navbar-light" id="nav" style="background: rgba(255, 255, 255, 1)">
	  <a class="navbar-brand" href="{% url 'app:all-notes' %}">Googol Notes</a>
	    <button class="navbar-toggler" style="outline: none; border: none;" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
	    	<ul class="navbar-nav mr-auto">
		      <div class="navbar-nav">
		        <a class="nav-link active" href="{% url 'app:all-notes' %}">Home <span class="sr-only">(current)</span></a>
		        {% if user.is_authenticated %}
		        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
		        <a class="nav-link" href="{% url 'app:search-note' %}">Search Notes</a>
		        {% else %}
		        <a class="nav-link" href="{% url 'accounts:login'  %}">Login</a>
		        <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
		        {% endif %}
		      </div>
		    </ul>
	    </div>
	</nav>

	<div class="container">
		{% block content %} {% endblock content %}
	</div>

</body>

<script type="text/javascript">
	const  navShadow = () => {
    var nav = document.getElementById("nav");
    var sticky = 70;

    if (window.pageYOffset > sticky) {
      nav.classList.add("add-shadow");
    } else {
      nav.classList.remove("add-shadow");
    }
  };

  window.addEventListener("scroll",  navShadow);
</script>

</html>